---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
- name: debian-7.6
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: centos-6.5

- name: windows-2012R2
  transport:
    name: winrm
  driver_config:
    box: win2012r2-datacenter-chef11.16.2
    vm_hostname: couchbase
    require_chef_omnibus: false

suites:
- name: server-community
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::server]
  attributes:
    couchbase:
      server:
        password: "whatever"

- name: server-enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::server]
  attributes:
    couchbase:
      server:
        edition: "enterprise"
        password: "whatever"
        version: "2.1.0"

- name: moxi
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::moxi]
  attributes: {}
  excludes: ["windows-2012R2"]

- name: client
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::client]
  attributes: {}
