---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
- name: debian-7.6
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: centos-6.5

- name: windows-2012R2
  driver:
    name: vagrant
    network:
      - ["private_network", { type: "dhcp" }]
  transport:
    name: winrm
  driver_config:
    gui: true
    box: mwrock/Windows2012R2Full
    customize:
      memory: 1024

suites:
- name: server-community
  provisioner:
    name: nodes
  run_list:
  - recipe[couchbase-tests::ipaddress]
  - recipe[couchbase::server]
  - recipe[export-node]
  attributes:
    couchbase:
      server:
        password: "whatever"

- name: second-node
  provisioner:
    name: nodes
  run_list:
  - recipe[couchbase-tests::ipaddress]
  - recipe[couchbase-tests::default]
  - recipe[export-node]
  attributes:
    couchbase:
      server:
        password: "whatever"

- name: server-enterprise
  run_list:
  - recipe[couchbase::server]
  - recipe[export-node]
  attributes:
    couchbase:
      server:
        edition: "enterprise"
        password: "whatever"
        version: "2.1.0"

- name: moxi
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::moxi]
  attributes: {}
  excludes: ["windows-2012R2"]

- name: client
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::client]
  attributes: {}
